# mysql ---------------------------------------------
datastore:
  image: busybox
  volumes:
      - /opt/datastore:/var/lib/mysql
  container_name: mysql-datastore
mysql:
  image: mysql:5.7
  environment:
    MYSQL_ROOT_PASSWORD: password
    MYSQL_DATABASE: study
    MYSQL_USER: docker
    MYSQL_PASSWORD: docker
  ports:
    - "3306:3306"
  volumes_from:
    - datastore
  container_name: mysql-db
# ---------------------------------------------------

# postgres ------------------------------------------
postgres-data:
  image: busybox
  volumes:
      - /var/lib/postgresql/data
  container_name: postgres-datastore

postgresql:
  image: postgres
  environment:
    POSTGRES_USER: docker
    POSTGRES_PASSWORD: docker
    POSTGRES_DB: study
  ports:
    - "5432:5432"
  container_name: postgres-db
  volumes_from:
      - postgres-data
# ---------------------------------------------------
